log_level "notice"
log_file "$XDG_CACHE_HOME/mpd/log"
music_directory "$HOME/Music"
playlist_directory "$XDG_CACHE_HOME/mpd/playlist"
bind_to_address "127.0.0.1"
database {
    plugin "simple"
    path "$XDG_CACHE_HOME/mpd/db"
    cache_directory "$XDG_CACHE_HOME/mpd/"
}

audio_output {
    type "pipewire"
    name "PipeWire"
}
