#!/bin/sh

# exit if no args
[ -z "$@" ] && exit 0

# exit unless running under tmux
[ -z "$TMUX" ] && exit 0

# exit unless stdout is connected to a terminal
[ -t 1 ] || exit 0

exec printf "\033k${@}\033\134"
